# Generated by ChatGPT on 2026-02-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=255)),
                ("is_pleasant", models.BooleanField(default=False)),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки (в днях)",
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)],
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Время на выполнение (в секундах), не больше 120",
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка, связанная с полезной",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_habits",
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="habits", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
